disableStartupPopups: false
gui:
  skipRewordInEditorWarning: true
  # Config relating to colors and styles.
  # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#color-attributes
  theme:
    activeBorderColor:
      - bold
    inactiveBorderColor:
      - default
    searchingActiveBorderColor:
      - cyan
      - bold
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - white
  skipDiscardChangeWarning: true
git:
  autoFetch: false
keybinding:
  files:
    commitChanges: C
    commitChangesWithEditor: c
  commits:
    renameCommit: R
    renameCommitWithEditor: r
